tcc/tcc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('website.urls')),
]

tcc/website/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),

    # Urls do login, cadastro e logout
    path('login/', views.logar, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('logout/', views.sair, name='logout'),

    # Urls dos laboratórios
    path('laboratorios/admin', views.AdminLaboratoriosListView.as_view(), name='admin_lista_laboratorios'),
    path('laboratorios/', views.LaboratoriosListView.as_view(), name='lista_laboratorios'),
    path('laboratorios/cadastrar', views.LaboratoriosCreateView.as_view(), name='cadastra_laboratorios'),
    path('laboratorios/excluir/<str:lab_codigo>/', views.LaboratoriosDeleteView.as_view(), name='exclui_laboratorios'),
    path('laboratorios/atualizar/<str:lab_codigo>/', views.LaboratoriosUpdateView.as_view(), name='atualiza_laboratorios'),

    # Urls dos usuários
    path('usuarios/', views.UsuariosListView.as_view(), name='lista_usuarios'),
    path('usuarios/atualizar/<int:pk>/', views.atualiza_usuarios, name='atualiza_usuarios'),
    path('usuarios/excluir/<int:pk>/', views.excluir_usuario, name='excluir_usuario'),

    path('usuarios/rejeitar/<int:user_id>/', views.rejeitar_usuario, name='rejeitar_usuario'),
    path('usuarios/aprovar/<int:user_id>/', views.aprovar_usuario, name='aprovar_usuario'),

    # Urls da agenda
    path('agenda/', views.agenda, name='agenda'),
    path('eventos/json/', views.reservas_json, name='reservas_json'),
    path('agenda/criar', views.CriarReserva.as_view(), name='criar_reserva'),

    # Urls das reservas
    path('reservas/reservar/<int:lab_codigo>/', views.CriarReserva.as_view(), name='reservar'),
    path('reservas/atualizar/<int:pk>/', views.AtualizarReserva.as_view(), name='atualizar_reserva'),
    path('reservas/excluir/<int:pk>/', views.ExcluirReserva.as_view(), name='excluir_reserva'),
    path('historico/', views.historico_reservas, name='historico'),
    path('historico/admin', views.historico_reservas_admin, name='historico_admin'),

    # Urls da escola
    path('escola/informações/', views.EscolaUpdateView.as_view(), name='escola'),
    path('buscar-cep/', views.buscar_cep, name='buscar-cep'),
    path('escola/', views.EscolaListView.as_view(), name='informacoes_escola'),

    # Urls de recuperação de senha
    path('senha-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
            email_template_name='registration/password_reset_email.txt',
            subject_template_name='registration/password_reset_subject.txt'), name='password_reset'),
            
    path('senha-reset/enviado/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('senha-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('senha-reset/feito/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('api/laboratorios/<int:lab_codigo>/horarios/', views.horarios_laboratorio, name='horarios_laboratorio'),
    path('verificar-disponibilidade/<int:lab_codigo>/', views.verificar_disponibilidade, name='verificar_disponibilidade'),
    path('api/laboratorios/<int:lab_codigo>/horarios-disponiveis/', views.horarios_disponiveis, name='horarios_disponiveis'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tcc/website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from cpf_field.models import CPFField
from django.forms import ValidationError
from multiselectfield import MultiSelectField
from django.core.validators import FileExtensionValidator, MinLengthValidator
from simple_history.models import HistoricalRecords, HistoricForeignKey

DIAS_SEMANA = [
    (0, 'Segunda-feira'),
    (1, 'Terça-feira'),
    (2, 'Quarta-feira'),
    (3, 'Quinta-feira'),
    (4, 'Sexta-feira'),
    (5, 'Sábado'),
    (6, 'Domingo'),
]


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("O email é obrigatório")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if not extra_fields.get("is_staff"):
            raise ValueError("O superusuário precisa ter is_staff=True.")
        if not extra_fields.get("is_superuser"):
            raise ValueError("O superusuário precisa ter is_superuser=True.")

        return self.create_user(email, password, **extra_fields)

class Usuarios(AbstractUser):
    email = models.EmailField(unique=True)
    cpf = CPFField('cpf')
    telefone = models.CharField(max_length=15)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    class Meta:
        db_table = 'tbl_usuarios'


class Equipamentos(models.Model):
    equip_codigo = models.AutoField(primary_key=True, db_column='equip_codigo')
    equip_nome = models.CharField(max_length=30, db_column='equip_nome')
    equip_descricao = models.TextField(db_column='equip_descricao')

    def __str__(self):
        return self.equip_nome
    
    class Meta:
        db_table = 'tbl_equipamentos'

class Laboratorios(models.Model):
    STATUS_ESCOLHA = [
        ('disponivel', 'Disponível'),
        ('usando', 'Em uso'),
        ('indisponivel', 'Indisponível')
    ]
    lab_codigo = models.AutoField(primary_key=True, db_column='lab_codigo')
    lab_nome = models.CharField(max_length=255, db_column='lab_nome')
    lab_descricao = models.TextField(blank=True, null=True, db_column='lab_descricao')
    lab_capacidade = models.IntegerField(db_column='lab_capacidade')
    lab_status = models.CharField(max_length=20, choices=STATUS_ESCOLHA, default='disponivel', db_column='lab_status')
    lab_foto = models.ImageField(default='icone_sala_aula.jpeg', blank=True, null=True, upload_to='uploads/')
    lab_equipamento = models.ManyToManyField(Equipamentos, through='LaboratorioEquipamento')

    def __str__(self):
        return self.lab_nome

    class Meta:
        db_table = 'tbl_laboratorios'

class LaboratorioEquipamento(models.Model):
    laboratorio = models.ForeignKey(Laboratorios, on_delete=models.CASCADE)
    equipamento = models.ForeignKey(Equipamentos, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('laboratorio', 'equipamento')

    def __str__(self):
        return f"{self.laboratorio.lab_nome} - {self.equipamento.equip_nome} ({self.quantidade})"

class Reservas(models.Model):
    REPETICAO_ESCOLHAS = [
        ('N', 'Não repetir'),
        ('D', 'Diariamente'),
        ('S', 'Semanalmente'),
        ('M', 'Mensalmente'),
        ('A', 'Anualmente'),
    ]
    res_codigo = models.AutoField(primary_key=True, db_column='res_codigo')
    res_inicio = models.DateTimeField(db_column='res_inicio')
    res_fim = models.DateTimeField(db_column='res_fim')
    res_repeticao = models.CharField(max_length=1, choices=REPETICAO_ESCOLHAS, default='N', db_column='res_repeticao')
    res_status = models.CharField(max_length=45, db_column='res_status')
    res_intervalo_semanas = models.PositiveIntegerField(null=True, blank=True, db_column='res_intervalo_semanas')
    res_dia_semana = models.CharField(
        max_length=13,
        null=True,
        blank=True,
        help_text="Dias para repetição semanal (0=Segunda, 6=Domingo)"
    )
    res_data_final_repeticao = models.DateField(null=True, blank=True, db_column='res_data_final_repeticao')
    res_descricao = models.TextField(blank=True, db_column='res_descricao')
    laboratorio = models.ForeignKey(
        Laboratorios, on_delete=models.CASCADE, related_name='laboratorio_reservas', db_column='lab_codigo_res'
    )
    professor = models.ForeignKey(Usuarios, on_delete=models.CASCADE, related_name='professor', db_column='professor_codigo_reserva')
    res_repeticao_original = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE, related_name='repeticoes', db_column='res_repeticao_original'
    )

    history = HistoricalRecords()
    class Meta:
        db_table = 'tbl_reservas'


class Disponibilidade(models.Model):
    hor_codigo = models.AutoField(primary_key=True, db_column='hor_codigo')
    hor_inicio = models.TimeField(db_column='hor_inicio')
    hor_fim = models.TimeField(db_column='hor_fim')
    hor_diasDisponiveis = models.CharField(
        max_length=13,
        db_column='hor_diasDisponiveis',
        blank=True,
        null=True,
        help_text="Dias da semana disponíveis (ex.: '0,1,2' para segunda, terça, quarta)"
    )
    laboratorio = models.ForeignKey(
        'Laboratorios',
        on_delete=models.CASCADE,
        related_name='disponibilidades',
        db_column='lab_codigo'
    )

    class Meta:
        db_table = 'tbl_horario_reserva'

    def __str__(self):
        return f"{self.hor_inicio.strftime('%H:%M')} - {self.hor_fim.strftime('%H:%M')}"

    def get_dias_semana_list(self):
        return self.hor_diasDisponiveis.split(',')

class Escola(models.Model):
    nome = models.CharField(max_length=100)
    logo = models.ImageField(default='sem_foto.jpeg', blank=True, upload_to='uploads/', null=True,
                             validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])
    cep = models.CharField(max_length=10, unique=True)
    cidade = models.CharField(max_length=255)
    estado = models.CharField(max_length=2)
    bairro = models.CharField(max_length=255, blank=True)
    endereco = models.CharField(max_length=255)
    telefone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(blank=True)
    horario_inicio = models.TimeField(null=True, blank=True)
    horario_fim = models.TimeField(null=True, blank=True)

    class Meta:
        db_table = 'tbl_escola'

    def __str__(self):
        return self.nome

tcc/website/templates/escola/atualizar_escola.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Escola{% endblock %}

{% block content %}

{% if messages %}
    <div class="w-full flex justify-center">
        {% for message in messages %}
            <div class="flex items-center justify-between px-4 py-3 text-white rounded-lg shadow-md
                {% if message.tags == 'error' %}
                    bg-red-600
                {% elif message.tags == 'success' %}
                    bg-green-600
                {% elif message.tags == 'warning' %}
                    bg-yellow-600
                {% else %}
                    bg-blue-600
                {% endif %}">
                <span>{{ message }}</span>
                <button type="button" class="ml-4 text-white hover:text-gray-200" onclick="this.parentElement.remove()">
                    &times;
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}

<div class="bg-white shadow-lg rounded-lg p-8 mx-4 mt-8">
    <h1 class="text-3xl font-extrabold text-center text-gray-800 mb-6">Informações da Escola</h1>
</div>

<div class="flex flex-wrap items-start justify-center gap-10 mt-8">
    <form method="post" enctype="multipart/form-data" class="flex flex-wrap gap-10 w-full justify-center bg-gray-50 p-6 rounded-lg shadow-lg">
        {% csrf_token %}

        <div class="relative group flex flex-col items-center w-full md:w-1/3">
            <h2 class="text-lg font-semibold text-gray-700 mb-2">Foto da Escola</h2>

            <div class="relative">
                <img id="image-preview" src="{% if form.logo.value.url %}{{ form.logo.value.url }}{% else %}{% static 'img/sem_foto.jpeg' %}{% endif %}"
                    alt=""
                    class="w-56 h-56 border-4 border-gray-200 rounded-full object-contain cursor-pointer transform transition duration-300 ease-in-out hover:scale-105"
                    data-full-image="{% if form.logo.value.url %}{{ form.logo.value.url }}{% else %}{% static 'img/sem_foto.jpeg' %}{% endif %}" onclick="expandImage('{{ form.logo.value.url }}')">
                <label for="id_logo"
                    class="absolute bottom-3 right-4 bg-gray-800 text-white p-2 rounded-full shadow-md hover:bg-gray-700 cursor-pointer transition-all ease-in-out duration-300 hover:scale-105">
                    <i data-lucide="camera"></i>
                </label>
                <span class="absolute bottom-3 left-4 bg-gray-800 text-white p-2 rounded-full shadow-md hover:bg-gray-700 cursor-pointer ease-in-out transition-all duration-300 hover:scale-105">
                    <i data-lucide="x" ></i>
                </span>
            </div>

            <input type="file" name="logo" accept="image/*" id="id_logo" class="hidden">
        </div>

        <div class="flex flex-wrap gap-6 justify-center w-full md:w-2/3">
            <div class="flex flex-col space-y-6 w-full md:w-1/2">
                <div>
                    {{ form.nome.label_tag }}
                    {{ form.nome }}
                </div>

                <div>
                    {{ form.telefone.label_tag }}
                    {{ form.telefone }}
                </div>

                <div>
                    {{ form.email.label_tag }}
                    {{ form.email }}
                </div>

                <div>
                    {{ form.horario_inicio.label_tag }}
                    {{ form.horario_inicio }}
                </div>
                
                <div>
                    {{ form.horario_fim.label_tag }}
                    {{ form.horario_fim }}
                </div>
            </div>

            <div class="flex flex-col space-y-6 w-full md:w-1/2">
                <div>
                    {{ form.cep.label_tag }}
                    {{ form.cep }}
                </div>

                <div>
                    {{ form.cidade.label_tag }}
                    {{ form.cidade }}
                </div>

                <div>
                    {{ form.estado.label_tag }}
                    {{ form.estado }}
                </div>

                <div>
                    {{ form.bairro.label_tag }}
                    {{ form.bairro }}
                </div>

                <div>
                    {{ form.endereco.label_tag }}
                    {{ form.endereco }}
                </div>
            </div>
        </div>

        <div class="w-full flex justify-center mt-8">
            <button type="submit" id="btns"
                class="flex items-center gap-3 bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg text-lg transition duration-300 ease-in-out transform hover:scale-105">
                <i data-lucide="check"></i>
                <span>Salvar</span>
            </button>
        </div>
    </form>
</div>

<div id="imageModal" class="fixed inset-0 bg-opacity-75 flex items-center justify-center z-50 hidden backdrop-blur-sm">
    <div class="relative bg-white p-4 rounded-lg shadow-xl">
        <img id="modalImage" class="max-w-[90vw] max-h-[90vh] rounded-lg shadow-md" />
        <button onclick="closeImageModal()" class="absolute top-4 right-4 text-white bg-gray-800 rounded-full p-2 shadow-md hover:bg-gray-700">
            <i data-lucide="x"></i>
        </button>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const removeButton = document.querySelector('.absolute.bottom-3.left-4');
        const imagePreview = document.getElementById('image-preview');
        const logoInput = document.getElementById('id_logo');

        if (removeButton && imagePreview && logoInput) {
            removeButton.addEventListener('click', function(e) {
                e.preventDefault();
                imagePreview.src = "{% static 'img/sem_foto.jpeg' %}";
                imagePreview.dataset.fullImage = "{% static 'img/sem_foto.jpeg' %}";
                logoInput.value = '';
            });
        }
    });
</script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const logoInput = document.getElementById('id_logo');
        const imagePreview = document.getElementById('image-preview');

        if (logoInput && imagePreview) {
            logoInput.addEventListener('change', function () {
                if (this.files && this.files[0]) {
                    const reader = new FileReader();

                    reader.onload = function (e) {
                        imagePreview.src = e.target.result;
                        imagePreview.dataset.fullImage = e.target.result;
                    }

                    reader.readAsDataURL(this.files[0]);
                }
            });

            document.querySelector('form').addEventListener('submit', function (e) {
                if (!logoInput.files.length && !imagePreview.src.includes('img/sem_foto.jpeg')) {
                    const hiddenInput = document.createElement('input');
                    hiddenInput.type = 'hidden';
                    hiddenInput.name = 'logo';
                    hiddenInput.value = '{{ form.logo.value|default:"" }}';
                    this.appendChild(hiddenInput);
                }
            });
        }
    });
</script>

<script>
    function expandImage(src) {
        document.getElementById('modalImage').src = src;
        document.getElementById('imageModal').classList.remove('hidden');
        document.body.style.overflow = 'hidden';
    }

    function closeImageModal() {
        document.getElementById('imageModal').classList.add('hidden');
        document.body.style.overflow = '';
    }

    document.querySelectorAll('.expandable-image').forEach(img => {
        img.addEventListener('click', () => {
            expandImage(img.dataset.fullImage);
        });
    });

    document.getElementById('id_cep').addEventListener('input', async function (e) {
        this.value = formatarCEP(this.value);

        const cep = this.value.replace(/\D/g, '');
        if (cep.length === 8) {
            await buscarCEP(this);
        }
        else if (cep.length < 8){
            document.getElementById('#btns').classList.add('hidden')
        }
    });

    function formatarCEP(value) {
        let cep = value.replace(/\D/g, '');
        if (cep.length > 5) {
            cep = cep.substring(0, 5) + '-' + cep.substring(5, 8);
        }
        return cep;
    }

    async function buscarCEP(input) {
        const cep = input.value.replace(/\D/g, '');

        if (input.dataset.loading === 'true') return;

        input.dataset.loading = 'true'; 
        const loadingElement = document.createElement('span');
        loadingElement.textContent = 'Buscando...';
        loadingElement.className = 'text-sm text-gray-500 ml-2';
        input.parentNode.appendChild(loadingElement);

        try {
            const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`);
            const data = await response.json();

            if (data.erro) {
                throw new Error('CEP não encontrado');
            }

            document.getElementById('id_cidade').value = data.localidade || '';
            document.getElementById('id_estado').value = data.uf || '';


        } catch (error) {
            console.error('Erro ao buscar CEP:', error);
            alert('CEP não encontrado. Por favor, verifique o número e tente novamente.');
        } finally {
            input.dataset.loading = 'false';
            if (loadingElement.parentNode) {
                loadingElement.remove();
            }
        }
    }
</script>

{% endblock %}

tcc/website/templates/escola/escola.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Detalhes da Escola{% endblock %}

{% block content %}
<div class="bg-white shadow-lg rounded-lg p-8 mx-4 mt-8">
    <h1 class="text-3xl font-extrabold text-center text-gray-800 mb-6">Informações da Escola</h1>

    <div class="flex justify-center items-center flex-col md:flex-row gap-10">
        {% for e in escola %}
            <div class="w-full md:w-1/3 flex justify-center">
                <img src="{{ e.logo.url }}" alt="Logo da Escola" class="w-56 h-56 border-4 border-gray-200 rounded-full object-contain cursor-pointer transform transition duration-300 ease-in-out hover:scale-105" onclick="expandImage('{{ e.logo.url }}')">
            </div>

            <div class="w-full md:w-2/3">
                <div class="space-y-6">
                    <div>
                        <h2 class="text-xl font-semibold text-gray-700">Nome</h2>
                        <p class="text-gray-600">{{ e.nome }}</p>
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold text-gray-700">Telefone</h2>
                        <p class="text-gray-600">{{ e.telefone }}</p>
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold text-gray-700">Email</h2>
                        <p class="text-gray-600">{{ e.email }}</p>
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold text-gray-700">Horário de Abertura</h2>
                        <p class="text-gray-600">{{ e.horario_inicio }}</p>
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold text-gray-700">Horário de Fechamento</h2>
                        <p class="text-gray-600">{{ e.horario_fim }}</p>
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold text-gray-700">Endereço</h2>
                        <p class="text-gray-600">{{ e.endereco }} - {{ e.bairro }}, {{ e.cidade }} - {{ e.estado }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<div id="imageModal" class="fixed inset-0 bg-opacity-75 flex items-center justify-center z-50 hidden backdrop-blur-sm">
    <div class="relative bg-white p-4 rounded-lg shadow-xl">
        <img id="modalImage" class="max-w-[90vw] max-h-[90vh] rounded-lg shadow-md" />
        <button onclick="closeImageModal()" class="absolute top-4 right-4 text-white bg-gray-800 rounded-full p-2 shadow-md hover:bg-gray-700">
            <i data-lucide="x"></i>
        </button>
    </div>
</div>

<script>
    function expandImage(src) {
        document.getElementById('modalImage').src = src;
        document.getElementById('imageModal').classList.remove('hidden');
        document.body.style.overflow = 'hidden';
    }

    function closeImageModal() {
        document.getElementById('imageModal').classList.add('hidden');
        document.body.style.overflow = '';
    }
</script>
{% endblock %}

tcc/website/templates/escola/upload_logo.html
<form method="POST", enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>